* 子龙山人的 Emacs 配置
Hacking 始于 2013 年。

** Emacs 爱好者交流平台
https://slackin-emacs-cn.herokuapp.com/
(邀请制限制已解除，欢迎大家加入，一起 Happy Hacking Emacs :smile:）

** 使用方法

#+BEGIN_SRC sh
  #clone spacemacs repo and use develop branch
  git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d
  cd .emacs.d
  git checkout --track origin/develop

  #clone zilongshanren layer and checkout develop branch
  git clone https://github.com/zilongshanren/spacemacs-private.git ~/.spacemacs.d/
#+END_SRC

现在可以打开 Emacs 24.5+ 开始使用我的配置了。

** 配置说明
1. 我的配置主要分成两个 layer，一个 zilongshanren layer 和一个 guanghui layer。zilongshanren layer 是对
   spacemacs 本身的一些扩展，也许将来某一天会被合进去。大家如果 fork 我的仓库，可以使用这个 layer。

2. 我个人的一些配置和快捷键绑定主要放到 guanghui layer 里面，大家也可以参考一下。我的这个 layer 使用了 evil。
   所以，对于 Vim 党来说会比较友好一点。

3. Spacemacs Rocks 系统视频演示：https://github.com/zilongshanren/Spacemacs-rocks/issues/5 , 让你从此爱上 Emacs :smile:

** 为什么要使用我的配置？
1. 使用我的配置有个好处是我每周会同步最新的 spacemacs 并且 update 所有的 package，保证配置可以用起来。
   （package 作者和 spacemacs 作者引入 的 bug 除外），不想折腾的人可以快速上手。

2. 另外关于我配置里面不懂的可以用中文给我提 issue。

3. 我的配置用了很长时间了，有些代码你可以 copy 过去，相信你也会喜欢的。

4. 最后，我的 spacemacs rocks 视频系列也是基于这份配置，看视频有疑问也可以看看配置。

** 可能会遇到的问题
1. 如果使用了 =.spacemacs.d= 目录来保存你的 spacemacs 配置，就不需要在 HOME 目录维护一个 =.spacemacs=文件了。 至于为什么要使用 =.spacemacs.d= 目录而不是 =.spacemacs= 文件，主要是方便分离自己的配置与 spacemacs 的配置，更新更容易。

** Happy Hacking:smile: 
